<a href="https://colab.research.google.com/github/Kfafa2024/AIML-1030/blob/Assignments/Week_2_Matrix_Math_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Creating a Matrix

# Loading library: importing numpy package
import numpy as np

# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [3]:
#Add two matrix
#creating matrix 1
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])
# matrix 2
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

#add the 2 matrixes
np.add (matrix_a, matrix_b)



array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [4]:
#subtract the 2 matrixes with the following command
matrix_a - matrix_b


array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [6]:
#create matrix a
matrix_a= np.array([[1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 2]])

#create matrix b
matrix_b= np.array([[1, 3, 1],
                    [1, 3, 1],
                    [1, 3, 8]])
#subtrat them with this function
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [7]:
#Matrix multiplication

#multiply by using np.dot

np.dot(matrix_a, matrix_b)


array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [8]:
#Matrix multiplication

#multiply by using @ operator

matrix_a @ matrix_b

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [9]:
#Matrix multiplication

#multiply by using element wise: Element-wise (Hadamard) Multiplication:
# You multiply each entry of one matrix by the corresponding entry in the same
#position in the other matrix.

matrix_a * matrix_b


array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

In [10]:
#Flip a matrix over its diagonal using the TRANSPOSE operation...
# uses the first created one as reference
matrix.T

array([[1, 1, 1],
       [2, 2, 2]])

In [13]:
#Change the signs of values across the main diagonal of a matrix
# by using the INVERSE function
np.linalg.pinv(matrix)

array([[0.06666667, 0.06666667, 0.06666667],
       [0.13333333, 0.13333333, 0.13333333]])

In [14]:
#Create a matrix using the arrange function
matrix2 = np.arange(1, 10) #10 is not inclusive
matrix2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#Reshape 1-D Matrix into 2-D matrix (3 rows and 3 columns)
matrix2 = matrix2.reshape(3, 3)

In [16]:
#Print the dimensions of a matrix
matrix2.ndim

1

In [17]:
#Print the number of elements in a matrix

matrix2.size

9

In [20]:
#Return the shape of a matrix
matrix2.shape

(3, 3)

In [21]:
#Return the maximum on along a given axis
np.max(matrix2)

np.int64(9)

In [22]:
#Print maximum element in each column
np.max(matrix2, axis=0)

array([7, 8, 9])

In [23]:
#Print maximum element in each row
np.max(matrix2, axis=1)

array([3, 6, 9])

In [24]:
#Return the maximum along a given axis
np.min(matrix2)

np.int64(1)

In [25]:
#Compute the mean of matrix2
np.mean(matrix2)

np.float64(5.0)

In [26]:
#Print the mean value in each column
np.mean(matrix2, axis=0)

array([4., 5., 6.])

In [27]:
#Print minimum element in each column
np.min(matrix2, axis=0)


array([1, 2, 3])

In [28]:
#Print minimum element in each column
np.min(matrix2, axis=1)


array([1, 4, 7])

In [29]:
#Mean of the matrix = sum of all elements of the matrix...
#Divided by the total elements of the matrix

#Print mean
np.mean(matrix2)

np.float64(5.0)

In [30]:
#Print mean value in each column
np.mean(matrix2, axis=0)

array([4., 5., 6.])